"""Corpus SDG tiếng Việt song song với sdg.xlsx gốc.

Gồm: tiêu đề 17 mục tiêu (bản LHQ/VN), 169 chỉ tiêu toàn cầu,
và câu hướng dẫn doanh nghiệp (SDG Compass / UN Global Compact)
dịch từ corpus tiếng Anh của paper — để mật độ tham chiếu gần bản gốc.
"""

from __future__ import annotations

from config import GOAL_TO_GP, GP_NAME

# (goalnum, sentence)
_ROWS: list[tuple[str, str]] = []


def _g(goal: int, *sentences: str) -> None:
    key = f"goal{goal:02d}"
    for s in sentences:
        s = " ".join(s.split())
        if s:
            _ROWS.append((key, s))


_g(
    1,
    "Chấm dứt mọi hình thức nghèo ở mọi nơi.",
    "Đến năm 2030, xóa bỏ tình trạng nghèo cùng cực cho tất cả mọi người ở mọi nơi, hiện được đo bằng số người sống dưới 1,25 đô la Mỹ một ngày.",
    "Đến năm 2030, giảm ít nhất một nửa tỷ lệ nam giới, nữ giới và trẻ em ở mọi lứa tuổi sống trong nghèo đói dưới mọi hình thức theo định nghĩa quốc gia.",
    "Thực hiện các hệ thống và biện pháp an sinh xã hội phù hợp với quốc gia cho tất cả mọi người, bao gồm sàn an sinh, và đến năm 2030 đạt mức bao phủ đáng kể cho người nghèo và người dễ bị tổn thương.",
    "Đến năm 2030, bảo đảm tất cả nam giới và nữ giới, đặc biệt người nghèo và người dễ bị tổn thương, có quyền bình đẳng đối với nguồn lực kinh tế, tiếp cận dịch vụ cơ bản, quyền sở hữu và kiểm soát đất đai cùng các hình thức tài sản khác, thừa kế, tài nguyên thiên nhiên, công nghệ phù hợp và dịch vụ tài chính, kể cả tài chính vi mô.",
    "Đến năm 2030, xây dựng khả năng chống chịu của người nghèo và người dễ bị tổn thương, giảm sự tiếp xúc và tổn thương của họ trước hiện tượng cực đoan liên quan khí hậu và các cú sốc, thảm họa kinh tế, xã hội, môi trường khác.",
    "Bảo đảm huy động đáng kể nguồn lực từ nhiều nguồn, kể cả qua hợp tác phát triển tăng cường, để cung cấp phương tiện đầy đủ và dự đoán được cho các nước đang phát triển thực hiện chương trình xóa nghèo.",
    "Tạo khung chính sách vững chắc ở cấp quốc gia, khu vực và quốc tế, dựa trên chiến lược phát triển vì người nghèo và nhạy cảm giới, để hỗ trợ đầu tư tăng tốc vào hành động xóa nghèo.",
    "Dù đã có tiến bộ theo các Mục tiêu Phát triển Thiên niên kỷ, khoảng 17% dân số thế giới — hơn 1 tỷ người — vẫn sống ở hoặc dưới 1,25 đô la Mỹ mỗi ngày.",
    "Một số nhóm bị đại diện quá mức trong người nghèo và gặp thêm ràng buộc như hạn chế tiếp cận nguồn lực sản xuất và thị trường: phụ nữ, người khuyết tật, trẻ em và người bản địa.",
    "Doanh nghiệp phải tôn trọng quyền con người, kể cả quyền của các nhóm dễ bị tổn thương.",
    "Doanh nghiệp có thể chủ động tháo gỡ rào cản thông qua mô hình kinh doanh bao trùm, sản phẩm và dịch vụ đổi mới phục vụ nhóm yếu thế, và tận dụng góc nhìn của họ với tư cách khách hàng, người lao động, nhà cung cấp, nhà phân phối và thành viên cộng đồng.",
    "Ngoài thu nhập, doanh nghiệp ảnh hưởng các chiều cạnh khác của nghèo: cơ hội hạn chế, năng lực hạn chế, mất an ninh lương thực, thiếu dịch vụ y tế, giáo dục, vệ sinh chất lượng, và mức trao quyền thấp.",
    "Nhiều chiều cạnh nghèo, đặc biệt với người nghèo, gắn với môi trường — sức khỏe bị ảnh hưởng trực tiếp bởi suy giảm chất lượng môi trường.",
    "Vai trò của doanh nghiệp trong xóa nghèo cũng gồm điều kiện khung, ví dụ đối thoại chính sách để cung cấp hàng hóa và dịch vụ cơ bản nơi doanh nghiệp hoạt động.",
    "Sẵn có sản phẩm và dịch vụ cho người có thu nhập thấp.",
    "Thu nhập, tiền lương và phúc lợi.",
    "Phát triển kinh tế tại các khu vực ưu tiên cao.",
    "Tiếp cận dịch vụ chăm sóc sức khỏe thiết yếu chất lượng.",
    "Tiếp cận nước, vệ sinh và vệ sinh cá nhân (WASH).",
    "Sẵn có và độ tin cậy của điện.",
    "Không phân biệt đối xử.",
    "Đầu tư vào hoạt động xóa nghèo do doanh nghiệp dẫn dắt, ví dụ xây dựng chính sách lương đủ sống.",
    "Mô hình kinh doanh bao trùm giúp người nghèo tham gia chuỗi giá trị với tư cách nhà sản xuất, nhà phân phối hoặc khách hàng.",
)

_g(
    2,
    "Xóa đói, bảo đảm an ninh lương thực, cải thiện dinh dưỡng và thúc đẩy nông nghiệp bền vững.",
    "Đến năm 2030, chấm dứt nạn đói và bảo đảm mọi người, đặc biệt người nghèo và người dễ bị tổn thương kể cả trẻ sơ sinh, được tiếp cận thực phẩm an toàn, bổ dưỡng và đủ quanh năm.",
    "Đến năm 2030, chấm dứt mọi hình thức suy dinh dưỡng, kể cả đạt được đến năm 2025 các mục tiêu đã thỏa thuận về thấp còi và gầy mòn ở trẻ dưới 5 tuổi, và đáp ứng nhu cầu dinh dưỡng của nữ vị thành niên, phụ nữ mang thai và cho con bú, người cao tuổi.",
    "Đến năm 2030, tăng gấp đôi năng suất nông nghiệp và thu nhập của hộ sản xuất nhỏ, đặc biệt phụ nữ, người bản địa, nông dân gia đình, người chăn nuôi và ngư dân, thông qua tiếp cận bình đẳng đất đai, nguồn lực, tri thức, dịch vụ tài chính, thị trường và cơ hội tạo giá trị gia tăng.",
    "Đến năm 2030, bảo đảm hệ thống sản xuất lương thực bền vững và thực hiện các thực hành nông nghiệp có khả năng chống chịu, tăng năng suất, giúp duy trì hệ sinh thái, tăng cường thích ứng với biến đổi khí hậu, hạn hán, lũ lụt và cải thiện dần chất lượng đất.",
    "Đến năm 2020, duy trì đa dạng di truyền của hạt giống, cây trồng, vật nuôi và các loài hoang dã liên quan, kể cả thông qua ngân hàng hạt giống đa dạng và quản lý tốt ở cấp quốc gia, khu vực, quốc tế.",
    "Tăng đầu tư, kể cả hợp tác quốc tế, vào hạ tầng nông thôn, nghiên cứu nông nghiệp, dịch vụ khuyến nông, phát triển công nghệ và ngân hàng gen cây trồng, vật nuôi.",
    "Sửa các hạn chế và méo mó thương mại trên thị trường nông sản thế giới, kể cả loại bỏ song song mọi hình thức trợ cấp xuất khẩu nông nghiệp.",
    "Áp dụng biện pháp bảo đảm hoạt động thị trường hàng hóa lương thực và phái sinh, tạo tiếp cận kịp thời thông tin thị trường, kể cả dự trữ, để hạn chế biến động giá quá mức.",
    "Lương thực và nông nghiệp nằm ở trung tâm của văn minh và thịnh vượng.",
    "Doanh nghiệp có thể góp phần xóa đói và cải thiện hệ thống lương thực, nông nghiệp.",
    "Thực phẩm lành mạnh với giá phải chăng.",
    "Ghi nhãn thực phẩm, an toàn thực phẩm và giá cả.",
    "Thu mua bền vững.",
    "Đa dạng di truyền của vật nuôi được nuôi trồng và thuần hóa.",
    "Thực hành lao động trong chuỗi cung ứng nông sản.",
    "Doanh nghiệp lớn thiết lập quan hệ kinh doanh dài hạn hỗ trợ hộ sản xuất nhỏ.",
    "Giảm tổn thất và lãng phí thực phẩm dọc chuỗi giá trị.",
    "Hỗ trợ nông dân tiếp cận tín dụng, bảo hiểm, giống, phân bón và thị trường.",
    "Không chuyển đổi đất nông nghiệp màu mỡ sang mục đích làm suy giảm an ninh lương thực.",
    "Thúc đẩy nông nghiệp hữu cơ, nông nghiệp thông minh với khí hậu và truy xuất nguồn gốc.",
)

_g(
    3,
    "Bảo đảm cuộc sống khỏe mạnh và tăng cường phúc lợi cho mọi người ở mọi lứa tuổi.",
    "Đến năm 2030, giảm tỷ số tử vong mẹ toàn cầu xuống dưới 70 trên 100.000 trẻ đẻ sống.",
    "Đến năm 2030, chấm dứt các trường hợp tử vong có thể phòng ngừa ở trẻ sơ sinh và trẻ dưới 5 tuổi; mọi quốc gia hướng tới giảm tử vong sơ sinh xuống ít nhất 12 trên 1.000 trẻ đẻ sống và tử vong dưới 5 tuổi xuống ít nhất 25 trên 1.000 trẻ đẻ sống.",
    "Đến năm 2030, chấm dứt dịch AIDS, lao, sốt rét, các bệnh nhiệt đới bị lãng quên, và chống viêm gan, các bệnh lây truyền qua nước và bệnh truyền nhiễm khác.",
    "Đến năm 2030, giảm một phần ba tử vong sớm do bệnh không lây nhiễm thông qua phòng ngừa, điều trị và thúc đẩy sức khỏe tâm thần và phúc lợi.",
    "Tăng cường phòng ngừa và điều trị lạm dụng chất, kể cả lạm dụng ma túy và sử dụng rượu có hại.",
    "Đến năm 2020, giảm một nửa số ca tử vong và thương tích toàn cầu do tai nạn giao thông.",
    "Đến năm 2030, bảo đảm tiếp cận phổ quát dịch vụ chăm sóc sức khỏe sinh sản và tình dục, kể cả kế hoạch hóa gia đình, thông tin, giáo dục và lồng ghép sức khỏe sinh sản vào chiến lược quốc gia.",
    "Đạt bao phủ y tế toàn dân, gồm bảo vệ rủi ro tài chính, tiếp cận dịch vụ y tế thiết yếu chất lượng, và tiếp cận thuốc, vắc-xin thiết yếu an toàn, hiệu quả, chất lượng, giá phải chăng.",
    "Đến năm 2030, giảm đáng kể số ca tử vong và bệnh tật do hóa chất độc hại, ô nhiễm không khí, nước, đất.",
    "Tăng cường thực thi Công ước khung của WHO về kiểm soát thuốc lá.",
    "Hỗ trợ nghiên cứu, phát triển vắc-xin và thuốc cho bệnh truyền nhiễm và không lây nhiễm chủ yếu ảnh hưởng nước đang phát triển; cung cấp tiếp cận thuốc, vắc-xin giá phải chăng.",
    "Tăng đáng kể tài chính y tế và tuyển dụng, phát triển, đào tạo, giữ chân nhân lực y tế ở các nước đang phát triển.",
    "Tăng cường năng lực mọi quốc gia, đặc biệt nước đang phát triển, về cảnh báo sớm, giảm rủi ro, quản lý rủi ro sức khỏe quốc gia và toàn cầu.",
    "Sức khỏe là quyền con người cơ bản và chỉ số then chốt của phát triển bền vững.",
    "An toàn và sức khỏe nghề nghiệp.",
    "Tiếp cận thuốc men.",
    "Tiếp cận dịch vụ chăm sóc sức khỏe thiết yếu chất lượng.",
    "Chất lượng không khí.",
    "Chất lượng nước.",
    "Hài hòa chính sách nhân sự với nguyên tắc quyền con người, kể cả chính sách HIV/AIDS.",
    "Đầu tư sức khỏe là ưu tiên trong hoạt động kinh doanh.",
    "Tạo điều kiện và đầu tư thuốc, chăm sóc sức khỏe giá phải chăng cho nhóm thu nhập thấp.",
    "Chương trình sức khỏe người lao động, khám sức khỏe định kỳ, bảo hiểm y tế.",
    "Giảm tai nạn lao động, bệnh nghề nghiệp và căng thẳng tại nơi làm việc.",
)

_g(
    4,
    "Bảo đảm giáo dục có chất lượng, công bằng, toàn diện và thúc đẩy cơ hội học tập suốt đời cho tất cả mọi người.",
    "Đến năm 2030, bảo đảm tất cả trẻ em gái và trai hoàn thành giáo dục tiểu học và trung học cơ sở miễn phí, công bằng, chất lượng, dẫn tới kết quả học tập phù hợp và hiệu quả.",
    "Đến năm 2030, bảo đảm tất cả trẻ em gái và trai được tiếp cận phát triển, chăm sóc và giáo dục mầm non chất lượng để sẵn sàng vào tiểu học.",
    "Đến năm 2030, bảo đảm tất cả nam nữ được tiếp cận bình đẳng giáo dục kỹ thuật, dạy nghề và đại học chất lượng, giá phải chăng, kể cả đại học.",
    "Đến năm 2030, tăng đáng kể số thanh niên và người lớn có kỹ năng phù hợp, kể cả kỹ năng kỹ thuật và nghề nghiệp, để việc làm, việc làm tử tế và khởi nghiệp.",
    "Đến năm 2030, xóa bỏ chênh lệch giới trong giáo dục và bảo đảm tiếp cận bình đẳng mọi cấp giáo dục và đào tạo nghề cho người dễ bị tổn thương, kể cả người khuyết tật, người bản địa và trẻ em hoàn cảnh khó khăn.",
    "Đến năm 2030, bảo đảm tất cả thanh niên và tỷ lệ đáng kể người lớn, cả nam và nữ, đạt xóa mù chữ và tính toán.",
    "Đến năm 2030, bảo đảm tất cả người học có kiến thức và kỹ năng cần thiết để thúc đẩy phát triển bền vững, kể cả giáo dục vì phát triển bền vững, lối sống bền vững, quyền con người, bình đẳng giới, văn hóa hòa bình, công dân toàn cầu và đa dạng văn hóa.",
    "Xây dựng và nâng cấp cơ sở giáo dục thân thiện trẻ em, người khuyết tật và giới, cung cấp môi trường học tập an toàn, không bạo lực, hòa nhập, hiệu quả cho tất cả.",
    "Đến năm 2020, tăng đáng kể số học bổng toàn cầu cho các nước đang phát triển để học đại học, kể cả đào tạo nghề, ICT, kỹ thuật, khoa học, kỹ thuật, toán.",
    "Đến năm 2030, tăng đáng kể cung cấp giáo viên đủ chất lượng, kể cả qua hợp tác quốc tế về đào tạo giáo viên ở các nước đang phát triển.",
    "Giáo dục là quyền con người cơ bản và không thể thiếu để đạt phát triển bền vững.",
    "Giáo dục vì phát triển bền vững.",
    "Sẵn có lực lượng lao động có kỹ năng.",
    "Nâng cao năng lực.",
    "Tác động gián tiếp tới tạo việc làm.",
    "Việc làm cho thanh niên.",
    "Cung cấp cho người lao động cơ hội liên tục nâng cao kỹ năng cho việc làm hiện tại và tương lai.",
    "Số giờ đào tạo trung bình mỗi năm trên mỗi lao động, theo giới và theo nhóm lao động.",
    "Biện pháp nâng cao kiến thức tập thể của cơ quan quản trị về chủ đề kinh tế, môi trường, xã hội.",
    "Học bổng, thực tập, hợp tác nhà trường – doanh nghiệp.",
    "Đào tạo kỹ năng số, an toàn lao động và đạo đức nghề nghiệp.",
)

_g(
    5,
    "Đạt được bình đẳng giới và trao quyền cho tất cả phụ nữ và trẻ em gái.",
    "Chấm dứt mọi hình thức phân biệt đối xử đối với phụ nữ và trẻ em gái ở mọi nơi.",
    "Loại bỏ mọi hình thức bạo lực đối với phụ nữ và trẻ em gái trên phạm vi công và tư, kể cả buôn người, bóc lột tình dục và các hình thức bóc lột khác.",
    "Loại bỏ mọi thực hành có hại như tảo hôn, hôn nhân trẻ em, hôn nhân cưỡng bức và cắt bỏ bộ phận sinh dục nữ.",
    "Thừa nhận và định giá công việc chăm sóc và công việc gia đình không lương thông qua cung cấp dịch vụ công, hạ tầng, chính sách bảo trợ xã hội, và thúc đẩy chia sẻ trách nhiệm trong hộ gia đình.",
    "Bảo đảm sự tham gia đầy đủ, hiệu quả và cơ hội lãnh đạo bình đẳng cho phụ nữ ở mọi cấp ra quyết định trong đời sống chính trị, kinh tế, công cộng.",
    "Bảo đảm tiếp cận phổ quát sức khỏe sinh sản và tình dục và quyền sinh sản.",
    "Tiến hành cải cách để phụ nữ có quyền bình đẳng đối với nguồn lực kinh tế, quyền sở hữu, kiểm soát đất đai và tài sản khác, dịch vụ tài chính, thừa kế, tài nguyên thiên nhiên.",
    "Tăng cường sử dụng công nghệ hỗ trợ, đặc biệt ICT, để thúc đẩy trao quyền cho phụ nữ.",
    "Thông qua và tăng cường chính sách vững chắc và pháp luật có thể thực thi để thúc đẩy bình đẳng giới và trao quyền cho mọi phụ nữ và trẻ em gái.",
    "Bình đẳng giới là quyền con người cơ bản, bất khả xâm phạm; trao quyền phụ nữ và trẻ em gái thiết yếu cho tăng trưởng kinh tế, phát triển xã hội và hiệu quả kinh doanh.",
    "Mọi doanh nghiệp có trách nhiệm nền tảng tôn trọng quyền con người, kể cả quyền của phụ nữ và trẻ em gái.",
    "Thù lao bình đẳng cho phụ nữ và nam giới.",
    "Đa dạng và cơ hội bình đẳng.",
    "Tiếp cận dịch vụ chăm sóc sức khỏe sinh sản và tình dục.",
    "Bạo lực và quấy rối tại nơi làm việc.",
    "Phụ nữ trong vị trí lãnh đạo.",
    "Dịch vụ và phúc lợi chăm sóc trẻ.",
    "Hỗ trợ tiếp cận dịch vụ chăm sóc trẻ và người phụ thuộc cho cả nữ và nam.",
    "Mở rộng quan hệ kinh doanh với doanh nghiệp do phụ nữ làm chủ, kể cả DNNVV và nữ doanh nhân.",
    "Theo dõi số liệu tách theo giới trong tuyển dụng, lương, thăng tiến, đào tạo.",
    "Chính sách không dung thứ quấy rối tình dục và phân biệt đối xử.",
    "Cân bằng cuộc sống – công việc, nghỉ thai sản/thai sản của nam, làm việc linh hoạt.",
)

_g(
    6,
    "Bảo đảm sẵn có và quản lý bền vững nước và vệ sinh cho tất cả mọi người.",
    "Đến năm 2030, đạt tiếp cận phổ quát và công bằng nước uống an toàn, giá phải chăng cho tất cả.",
    "Đến năm 2030, đạt tiếp cận đầy đủ và công bằng vệ sinh và vệ sinh cá nhân cho tất cả, đặc biệt chú ý nhu cầu của phụ nữ, trẻ em gái và người dễ bị tổn thương.",
    "Đến năm 2030, cải thiện chất lượng nước bằng cách giảm ô nhiễm, loại bỏ đổ thải, giảm thiểu phát thải hóa chất và vật liệu độc hại, giảm một nửa tỷ lệ nước thải chưa xử lý, tăng đáng kể tái sử dụng và tái chế an toàn trên toàn cầu.",
    "Đến năm 2030, tăng đáng kể hiệu quả sử dụng nước trên mọi ngành, bảo đảm khai thác và cung cấp nước ngọt bền vững để giải quyết khan hiếm nước, giảm đáng kể số người chịu khan hiếm nước.",
    "Đến năm 2030, thực hiện quản lý tài nguyên nước tổng hợp ở mọi cấp, kể cả qua hợp tác xuyên biên giới khi phù hợp.",
    "Đến năm 2020, bảo vệ và phục hồi các hệ sinh thái liên quan đến nước, kể cả núi, rừng, vùng đất ngập nước, sông, tầng chứa nước và hồ.",
    "Đến năm 2030, mở rộng hợp tác và hỗ trợ năng lực quốc tế cho các nước đang phát triển về nước và vệ sinh, kể cả thu gom nước, khử muối, hiệu quả nước, xử lý nước thải, công nghệ tái sử dụng.",
    "Hỗ trợ và tăng cường sự tham gia của cộng đồng địa phương trong cải thiện quản lý nước và vệ sinh.",
    "Tiếp cận nước và vệ sinh là quyền con người cơ bản và thách thức then chốt của phát triển bền vững.",
    "Khai thác nước bền vững.",
    "Cải thiện chất lượng nước thông qua xử lý nước thải.",
    "Cải thiện hiệu quả nước theo nguyên tắc 5R: giảm, tái sử dụng, thu hồi, tái chế, bổ sung.",
    "Tiếp cận nước, vệ sinh, vệ sinh cá nhân bình đẳng, giá phải chăng, an toàn cho người lao động và cộng đồng.",
    "Bảo vệ hệ sinh thái và đa dạng sinh học liên quan đến nước.",
    "Giảm ô nhiễm nước bằng quy trình xử lý nước thải hiện đại trước khi xả.",
    "Đầu tư xử lý nước để không làm quá tải hệ thống xử lý đô thị bởi nước thải công nghiệp.",
    "Thu gom và xử lý nước chảy tràn nông nghiệp, dùng lại như nguồn nước ngọt.",
    "Tái sử dụng nước xám trong vận hành tòa nhà, giảm nước sạch dùng xả toilet.",
    "Đo lường, công bố lượng nước tiêu thụ, cường độ nước và rủi ro nước trong chuỗi cung ứng.",
    "Không xả nước thải chưa xử lý ra sông, hồ, biển.",
)

_g(
    7,
    "Bảo đảm tiếp cận năng lượng hiện đại, bền vững, đáng tin cậy, giá phải chăng cho tất cả mọi người.",
    "Đến năm 2030, bảo đảm tiếp cận phổ quát dịch vụ năng lượng giá phải chăng, đáng tin cậy, hiện đại.",
    "Đến năm 2030, tăng đáng kể tỷ lệ năng lượng tái tạo trong cơ cấu năng lượng toàn cầu.",
    "Đến năm 2030, tăng gấp đôi tốc độ cải thiện hiệu quả năng lượng toàn cầu.",
    "Đến năm 2030, tăng hợp tác quốc tế để tạo điều kiện tiếp cận nghiên cứu và công nghệ năng lượng sạch, kể cả năng lượng tái tạo, hiệu quả năng lượng, nhiên liệu hóa thạch tiên tiến sạch hơn, và thúc đẩy đầu tư vào hạ tầng và công nghệ năng lượng sạch.",
    "Đến năm 2030, mở rộng hạ tầng và nâng cấp công nghệ cung cấp dịch vụ năng lượng hiện đại, bền vững cho tất cả ở các nước đang phát triển.",
    "Xã hội hiện đại phụ thuộc vào dịch vụ năng lượng đáng tin cậy, giá phải chăng để vận hành trơn tru và phát triển công bằng.",
    "Tiếp cận điện.",
    "Sẵn có và độ tin cậy của điện.",
    "Năng lượng tái tạo.",
    "Hiệu quả năng lượng.",
    "Đầu tư hạ tầng.",
    "Đầu tư môi trường.",
    "Cam kết cung cấp 100% nhu cầu điện vận hành từ nguồn tái tạo.",
    "Đầu tư R&D dịch vụ năng lượng bền vững, đưa công nghệ mới ra thị trường nhanh.",
    "Mức tiêu thụ năng lượng trong tổ chức.",
    "Giảm cường độ năng lượng trên đơn vị sản phẩm.",
    "Điện mặt trời mái, điện gió, sinh khối, và mua chứng chỉ năng lượng tái tạo.",
    "Tuyên bố rủi ro năng lượng và lộ trình chuyển dịch năng lượng.",
)

_g(
    8,
    "Thúc đẩy tăng trưởng kinh tế bền vững, bao trùm, liên tục, việc làm đầy đủ, năng suất và việc làm tử tế cho tất cả mọi người.",
    "Duy trì tăng trưởng kinh tế đầu người phù hợp với điều kiện quốc gia, và tăng trưởng GDP ít nhất 7% mỗi năm ở các nước kém phát triển.",
    "Đạt mức năng suất kinh tế cao hơn thông qua đa dạng hóa, nâng cấp công nghệ, đổi mới, kể cả tập trung vào ngành thâm dụng lao động và giá trị gia tăng cao.",
    "Thúc đẩy chính sách lấy phát triển làm trung tâm, hỗ trợ hoạt động sản xuất, tạo việc làm tử tế, khởi nghiệp, sáng tạo, đổi mới, và khuyến khích chính thức hóa, tăng trưởng DNNVV, kể cả tiếp cận dịch vụ tài chính.",
    "Đến năm 2030, cải thiện dần hiệu quả tài nguyên toàn cầu trong tiêu dùng và sản xuất, và nỗ lực tách tăng trưởng kinh tế khỏi suy thoái môi trường.",
    "Đến năm 2030, đạt việc làm đầy đủ, năng suất và việc làm tử tế cho tất cả phụ nữ, nam giới, kể cả thanh niên và người khuyết tật, và thù lao bình đẳng cho công việc có giá trị ngang nhau.",
    "Đến năm 2020, giảm đáng kể tỷ lệ thanh niên không có việc làm, học tập hoặc đào tạo.",
    "Áp dụng biện pháp ngay lập tức, hiệu quả để xóa lao động cưỡng bức, chấm dứt chế độ nô lệ hiện đại và buôn người, cấm và loại bỏ các hình thức lao động trẻ em tồi tệ nhất, kể cả tuyển dụng và sử dụng trẻ em lính, và đến năm 2025 chấm dứt lao động trẻ em dưới mọi hình thức.",
    "Bảo vệ quyền lao động và thúc đẩy môi trường làm việc an toàn, an ninh cho tất cả người lao động, kể cả lao động di cư, đặc biệt nữ di cư, và người làm việc bấp bênh.",
    "Đến năm 2030, xây dựng và thực hiện chính sách thúc đẩy du lịch bền vững tạo việc làm, thúc đẩy văn hóa, sản phẩm địa phương.",
    "Tăng cường năng lực thể chế tài chính trong nước để khuyến khích, mở rộng tiếp cận dịch vụ ngân hàng, bảo hiểm, tài chính cho tất cả.",
    "Khoảng một nửa dân số thế giới vẫn sống với mức tương đương khoảng 2 đô la Mỹ một ngày, và ở nhiều nơi có việc làm vẫn không bảo đảm thoát nghèo.",
    "Doanh nghiệp là động cơ tạo việc làm và tăng trưởng kinh tế, thúc đẩy hoạt động kinh tế qua chuỗi giá trị.",
    "Cơ hội việc làm tử tế có lợi cho cả doanh nghiệp và xã hội.",
    "Việc làm.",
    "Hòa nhập kinh tế.",
    "Không phân biệt đối xử.",
    "Hợp đồng lao động, bảo hiểm xã hội, lương đủ sống, đối thoại với người lao động.",
    "Không sử dụng lao động trẻ em, lao động cưỡng bức trong hoạt động và chuỗi cung ứng.",
    "An toàn lao động, giờ làm việc hợp lý, chống quấy rối.",
    "Tạo việc làm cho thanh niên, người khuyết tật, lao động địa phương.",
    "Năng suất lao động, đổi mới quy trình, chuyển đổi số có trách nhiệm.",
)

_g(
    9,
    "Xây dựng hạ tầng có khả năng chống chịu, thúc đẩy công nghiệp hóa bao trùm, bền vững, và tăng cường đổi mới.",
    "Phát triển hạ tầng chất lượng, đáng tin cậy, bền vững, có khả năng chống chịu, kể cả hạ tầng khu vực và xuyên biên giới, để hỗ trợ phát triển kinh tế và phúc lợi con người, tập trung tiếp cận giá phải chăng, công bằng cho tất cả.",
    "Thúc đẩy công nghiệp hóa bao trùm, bền vững, và đến năm 2030 tăng đáng kể tỷ lệ việc làm và GDP của ngành công nghiệp, phù hợp điều kiện quốc gia, và tăng gấp đôi tỷ lệ này ở các nước kém phát triển.",
    "Tăng tiếp cận dịch vụ tài chính cho DNNVV công nghiệp và khác, kể cả tín dụng giá phải chăng, và hòa nhập vào chuỗi giá trị, thị trường.",
    "Đến năm 2030, nâng cấp hạ tầng và cải tạo ngành công nghiệp để bền vững, tăng hiệu quả tài nguyên, áp dụng công nghệ, quy trình công nghiệp sạch, thân thiện môi trường.",
    "Tăng cường nghiên cứu khoa học, nâng cao năng lực công nghệ của ngành công nghiệp ở mọi quốc gia, đặc biệt nước đang phát triển, kể cả đến năm 2030 khuyến khích đổi mới, tăng đáng kể số lao động nghiên cứu trên 1 triệu dân, chi R&D công và tư.",
    "Tạo điều kiện phát triển hạ tầng bền vững, có khả năng chống chịu ở các nước đang phát triển qua hỗ trợ tài chính, công nghệ, kỹ thuật.",
    "Hỗ trợ phát triển công nghệ trong nước, nghiên cứu, đổi mới ở các nước đang phát triển, kể cả bảo đảm môi trường chính sách thuận lợi cho đa dạng hóa công nghiệp và giá trị gia tăng hàng hóa.",
    "Tăng đáng kể tiếp cận ICT, nỗ lực cung cấp tiếp cận Internet phổ quát, giá phải chăng ở các nước kém phát triển.",
    "Hạ tầng già cỗi, xuống cấp hoặc không tồn tại khiến việc kinh doanh tốt trở nên khó khăn.",
    "Đầu tư hạ tầng.",
    "Tiếp cận dịch vụ tài chính.",
    "Đầu tư môi trường.",
    "Nghiên cứu và phát triển.",
    "Di sản công nghệ.",
    "Mở rộng địa bàn cơ sở R&D, đưa năng lực nghiên cứu tới nước đang phát triển.",
    "Thiết lập tiêu chuẩn và thúc đẩy quy định bảo đảm dự án, sáng kiến của công ty được quản lý bền vững.",
    "Hợp tác với NGO và khu vực công để thúc đẩy tăng trưởng bền vững tại nước đang phát triển.",
    "Phát triển và tác động của đầu tư hạ tầng và dịch vụ được hỗ trợ.",
    "Chuyển đổi số, công nghiệp 4.0, đổi mới xanh, bằng sáng chế sạch.",
    "Hạ tầng chống chịu khí hậu, logistics xanh, khu công nghiệp sinh thái.",
)

_g(
    10,
    "Giảm bất bình đẳng trong và giữa các quốc gia.",
    "Đến năm 2030, đạt và duy trì tăng trưởng thu nhập của 40% dân số nghèo nhất ở mức cao hơn mức trung bình quốc gia.",
    "Đến năm 2030, trao quyền và thúc đẩy hòa nhập xã hội, kinh tế, chính trị cho tất cả, không phân biệt tuổi, giới, khuyết tật, chủng tộc, dân tộc, nguồn gốc, tôn giáo, điều kiện kinh tế hay khác.",
    "Bảo đảm cơ hội bình đẳng, giảm bất bình đẳng kết quả, kể cả bằng xóa bỏ luật, chính sách, thực hành phân biệt đối xử, và thúc đẩy pháp luật, chính sách, hành động phù hợp.",
    "Áp dụng chính sách, đặc biệt chính sách tài khóa, tiền lương, bảo trợ xã hội, và đạt dần bình đẳng lớn hơn.",
    "Cải thiện điều tiết và giám sát thị trường, thể chế tài chính toàn cầu, tăng cường thực thi các điều tiết đó.",
    "Bảo đảm đại diện, tiếng nói tăng lên của các nước đang phát triển trong quá trình ra quyết định tại các thể chế kinh tế, tài chính quốc tế.",
    "Tạo điều kiện di cư, di chuyển có trật tự, an toàn, có quy củ, có trách nhiệm của người dân, kể cả qua thực hiện chính sách di cư có kế hoạch, quản lý tốt.",
    "Thực hiện nguyên tắc đối xử đặc biệt và khác biệt cho các nước đang phát triển, đặc biệt nước kém phát triển, phù hợp với các thỏa thuận WTO.",
    "Khuyến khích hỗ trợ ODA và dòng tài chính, kể cả đầu tư trực tiếp nước ngoài, tới các quốc gia cần nhất.",
    "Đến năm 2030, giảm chi phí giao dịch kiều hối người di cư xuống dưới 3%, loại bỏ hành lang kiều hối có chi phí trên 5%.",
    "Bất bình đẳng thu nhập và của cải đang nghiêm trọng và ngày càng nới rộng trên toàn cầu.",
    "Mọi doanh nghiệp có trách nhiệm tôn trọng quyền con người.",
    "Doanh nghiệp nên tương tác với chính phủ một cách minh bạch, chịu trách nhiệm, và công bố khoản thanh toán cho chính phủ.",
    "Sẵn có sản phẩm, dịch vụ cho người thu nhập thấp.",
    "Tiếp cận dịch vụ tài chính.",
    "Thù lao bình đẳng cho phụ nữ và nam giới.",
    "Nâng cao năng lực.",
    "Đa dạng và cơ hội bình đẳng.",
    "Hòa nhập kinh tế.",
    "Đầu tư hoạt động xóa nghèo do doanh nghiệp dẫn dắt, ví dụ chính sách lương đủ sống.",
    "Hợp tác với mạng lưới xã hội dân sự để đào tạo kỹ năng giáo dục và khởi nghiệp.",
    "Không phân biệt đối xử vì dân tộc, tôn giáo, khuyết tật, xu hướng tình dục, xuất thân.",
    "Thu hẹp khoảng cách lương, tăng việc làm cho nhóm yếu thế, tài chính bao trùm.",
)

_g(
    11,
    "Làm cho đô thị và khu định cư của con người trở nên bao trùm, an toàn, có khả năng chống chịu và bền vững.",
    "Đến năm 2030, bảo đảm tiếp cận nhà ở đầy đủ, an toàn, giá phải chăng và dịch vụ cơ bản cho tất cả, nâng cấp khu ổ chuột.",
    "Đến năm 2030, cung cấp tiếp cận hệ thống giao thông an toàn, giá phải chăng, dễ tiếp cận, bền vững cho tất cả, cải thiện an toàn giao thông, đặc biệt mở rộng giao thông công cộng, chú ý nhóm dễ bị tổn thương, phụ nữ, trẻ em, người khuyết tật, người cao tuổi.",
    "Đến năm 2030, tăng cường đô thị hóa bao trùm, bền vững và năng lực tham gia, quy hoạch, quản lý định cư tổng hợp ở mọi quốc gia.",
    "Tăng cường nỗ lực bảo vệ, gìn giữ di sản văn hóa, thiên nhiên thế giới.",
    "Đến năm 2030, giảm đáng kể số người chết, số người bị ảnh hưởng, tổn thất kinh tế tương đối so với GDP toàn cầu do thảm họa, kể cả thảm họa liên quan nước, tập trung bảo vệ người nghèo và người dễ bị tổn thương.",
    "Đến năm 2030, giảm tác động môi trường bất lợi bình quân đầu người của đô thị, kể cả chú ý đặc biệt chất lượng không khí, quản lý chất thải đô thị và chất thải khác.",
    "Đến năm 2030, cung cấp tiếp cận phổ quát không gian xanh, công cộng an toàn, bao trùm, dễ tiếp cận, đặc biệt cho phụ nữ, trẻ em, người cao tuổi, người khuyết tật.",
    "Hỗ trợ mối liên kết kinh tế, xã hội, môi trường tích cực giữa đô thị, ngoại ô, nông thôn bằng tăng cường quy hoạch phát triển quốc gia, vùng.",
    "Đến năm 2020, tăng đáng kể số thành phố, định cư áp dụng, thực hiện chính sách, kế hoạch tổng hợp hướng tới bao trùm, hiệu quả tài nguyên, thích ứng, giảm nhẹ biến đổi khí hậu, chống chịu thảm họa.",
    "Hỗ trợ các nước kém phát triển, kể cả qua hỗ trợ tài chính, kỹ thuật, xây dựng tòa nhà bền vững, có khả năng chống chịu sử dụng vật liệu địa phương.",
    "Đến năm 2050, 70% dân số thế giới sống ở đô thị, khiến đô thị then chốt để đạt tương lai bền vững.",
    "Tiếp cận nhà ở giá phải chăng.",
    "Đầu tư hạ tầng.",
    "Giao thông bền vững.",
    "Tiếp cận không gian công cộng.",
    "Tòa nhà bền vững.",
    "Phát triển và tác động của đầu tư hạ tầng và dịch vụ được hỗ trợ.",
    "Số lượng và biến động phần trăm người sống ở khu vực bị ảnh hưởng bởi tiếng ồn.",
    "Quy hoạch đô thị, nông thôn bền vững, phân bổ dân cư, lao động hợp lý theo vùng.",
    "An toàn cháy nổ, PCCC, phòng chống thiên tai tại cơ sở.",
    "Giảm ùn tắc, khuyến khích xe điện, đi bộ, xe đạp, giao thông công cộng.",
)

_g(
    12,
    "Bảo đảm mô hình sản xuất và tiêu dùng bền vững.",
    "Thực hiện Khung chương trình 10 năm về sản xuất và tiêu dùng bền vững, mọi quốc gia hành động, các nước phát triển đi đầu, tính đến năng lực phát triển của nước đang phát triển.",
    "Đến năm 2030, đạt quản lý bền vững và sử dụng hiệu quả tài nguyên thiên nhiên.",
    "Đến năm 2030, giảm một nửa lãng phí thực phẩm bình quân đầu người ở cấp bán lẻ, tiêu dùng, và giảm tổn thất lương thực dọc chuỗi sản xuất, cung ứng, kể cả tổn thất sau thu hoạch.",
    "Đến năm 2020, đạt quản lý thân thiện môi trường đối với hóa chất và chất thải suốt vòng đời, theo khung quốc tế đã thỏa thuận, giảm đáng kể phát thải ra không khí, nước, đất để giảm thiểu tác động bất lợi lên sức khỏe con người và môi trường.",
    "Đến năm 2030, giảm đáng kể phát sinh chất thải thông qua phòng ngừa, giảm thiểu, tái chế, tái sử dụng.",
    "Khuyến khích công ty, đặc biệt công ty lớn, xuyên quốc gia, áp dụng thực hành bền vững, lồng ghép thông tin bền vững vào chu kỳ báo cáo.",
    "Thúc đẩy thực hành mua sắm công bền vững, phù hợp chính sách, ưu tiên quốc gia.",
    "Đến năm 2030, bảo đảm mọi người ở mọi nơi có thông tin, nhận thức phù hợp cho phát triển bền vững và lối sống hài hòa với thiên nhiên.",
    "Hỗ trợ nước đang phát triển tăng cường năng lực khoa học, công nghệ hướng tới mô hình sản xuất, tiêu dùng bền vững.",
    "Xây dựng, thực hiện công cụ giám sát tác động phát triển bền vững của du lịch bền vững tạo việc làm, thúc đẩy văn hóa, sản phẩm địa phương.",
    "Hợp lý hóa trợ cấp nhiên liệu hóa thạch không hiệu quả, khuyến khích tiêu dùng lãng phí, bằng cách loại bỏ méo mó thị trường.",
    "Ngày càng nhiều người gia nhập tầng lớp trung lưu trong hai thập kỷ tới.",
    "Doanh nghiệp có lợi ích tìm giải pháp mới cho sản xuất và tiêu dùng bền vững.",
    "Thu mua bền vững.",
    "Hiệu quả tài nguyên của sản phẩm và dịch vụ.",
    "Tái chế vật liệu.",
    "Thực hành mua sắm.",
    "Thông tin và ghi nhãn sản phẩm, dịch vụ.",
    "Tổng lượng nước tiêu thụ trong năm báo cáo trên toàn bộ hoạt động.",
    "Hiệu quả nước trong chuỗi giá trị.",
    "Tỷ lệ vật liệu sử dụng là đầu vào tái chế.",
    "Mức độ giảm thiểu tác động môi trường của sản phẩm và dịch vụ.",
    "Kinh tế tuần hoàn, thiết kế sinh thái, trách nhiệm mở rộng của nhà sản xuất.",
    "Giảm nhựa dùng một lần, bao bì xanh, vòng đời sản phẩm.",
)

_g(
    13,
    "Hành động khẩn cấp để chống biến đổi khí hậu và tác động của nó.",
    "Tăng cường khả năng chống chịu và thích ứng với rủi ro liên quan khí hậu và thiên tai ở mọi quốc gia.",
    "Lồng ghép biện pháp biến đổi khí hậu vào chính sách, chiến lược, quy hoạch quốc gia.",
    "Cải thiện giáo dục, nâng cao nhận thức, năng lực con người, thể chế về giảm nhẹ, thích ứng, giảm tác động, cảnh báo sớm biến đổi khí hậu.",
    "Thực hiện cam kết của các nước phát triển đối với Công ước khung của LHQ về biến đổi khí hậu, huy động 100 tỷ đô la Mỹ mỗi năm vào năm 2020 từ mọi nguồn để đáp ứng nhu cầu nước đang phát triển, vận hành Quỹ Khí hậu Xanh.",
    "Thúc đẩy cơ chế tăng năng lực hoạch định, quản lý liên quan biến đổi khí hậu ở các nước kém phát triển, quốc đảo nhỏ đang phát triển, tập trung phụ nữ, thanh niên, cộng đồng địa phương, nhóm bị gạt ra ngoài.",
    "Biến đổi khí hậu do phát thải nhân tạo CO2 và khí nhà kính khác. Tác động gồm tăng nhiệt độ bề mặt trung bình toàn cầu, thời tiết cực đoan, thay đổi mưa, nước biển dâng, axit hóa đại dương.",
    "Những tác động đó ảnh hưởng các SDG khác và thường khiến việc đạt chúng khó hơn.",
    "Hiệu quả năng lượng.",
    "Đầu tư môi trường.",
    "Phát thải khí nhà kính.",
    "Rủi ro và cơ hội do biến đổi khí hậu.",
    "Cải tạo hệ thống chiếu sáng cơ sở sang đèn LED tiết kiệm năng lượng.",
    "Hiểu rủi ro khí hậu và xây dựng khả năng chống chịu vào tài sản, chuỗi cung ứng của công ty.",
    "Mở rộng quản lý rừng bền vững qua thu mua có trách nhiệm và thay thế sản phẩm.",
    "Phát thải khí nhà kính trực tiếp (Phạm vi 1).",
    "Phát thải khí nhà kính gián tiếp từ năng lượng (Phạm vi 2).",
    "Phát thải khí nhà kính gián tiếp khác (Phạm vi 3).",
    "Cam kết Net Zero, khoa học dựa trên SBTi, định giá carbon nội bộ.",
    "Thích ứng khí hậu, bảo hiểm rủi ro thiên tai, kế hoạch liên tục hoạt động.",
    "Trồng rừng, tín chỉ carbon, năng lượng tái tạo, logistics thấp carbon.",
)

_g(
    14,
    "Bảo tồn và sử dụng bền vững đại dương, biển và tài nguyên biển cho phát triển bền vững.",
    "Đến năm 2025, ngăn chặn và giảm đáng kể mọi dạng ô nhiễm biển, đặc biệt từ hoạt động trên đất liền, kể cả rác thải biển và ô nhiễm dinh dưỡng.",
    "Đến năm 2020, quản lý, bảo vệ bền vững hệ sinh thái biển, ven biển để tránh tác động bất lợi đáng kể, kể cả tăng cường chống chịu, hành động phục hồi để đạt đại dương khỏe mạnh, năng suất.",
    "Giảm thiểu, giải quyết tác động axit hóa đại dương, kể cả qua hợp tác khoa học ở mọi cấp.",
    "Đến năm 2020, điều tiết hiệu quả việc khai thác, chấm dứt đánh bắt quá mức, đánh bắt bất hợp pháp, không báo cáo, không theo quy định, và thực hành đánh bắt hủy diệt; thực hiện kế hoạch quản lý dựa khoa học để phục hồi đàn cá trong thời gian ngắn nhất khả thi.",
    "Đến năm 2020, bảo tồn ít nhất 10% vùng ven biển, biển, phù hợp luật quốc gia, quốc tế, dựa trên thông tin khoa học tốt nhất.",
    "Đến năm 2020, cấm một số hình thức trợ cấp nghề cá góp phần dư thừa công suất, đánh bắt quá mức, loại bỏ trợ cấp góp phần đánh bắt IUU.",
    "Đến năm 2030, tăng lợi ích kinh tế cho các quốc đảo nhỏ đang phát triển, nước kém phát triển từ sử dụng bền vững tài nguyên biển, kể cả quản lý bền vững nghề cá, nuôi trồng, du lịch.",
    "Tăng kiến thức khoa học, phát triển năng lực nghiên cứu, chuyển giao công nghệ biển để cải thiện sức khỏe đại dương, tăng đóng góp đa dạng sinh học biển cho phát triển nước đang phát triển.",
    "Cung cấp tiếp cận cho ngư dân thủ công nhỏ đối với tài nguyên biển, thị trường.",
    "Tăng cường bảo tồn, sử dụng bền vững đại dương, tài nguyên biển bằng thực thi luật quốc tế như phản ánh trong UNCLOS.",
    "Đại dương đối mặt ô nhiễm biển, ô nhiễm dinh dưỡng, cạn kiệt tài nguyên và biến đổi khí hậu, chủ yếu do hành động của con người.",
    "Đa dạng sinh học biển.",
    "Axit hóa đại dương.",
    "Đầu tư môi trường.",
    "Sự cố tràn dầu, hóa chất.",
    "Thu mua bền vững.",
    "Xả nước ra đại dương.",
    "Cải thiện hiệu quả tài nguyên bằng tạo giá trị từ chất thải.",
    "Ngăn chặn quản lý chất thải kém hoặc xả rác có thể gây ô nhiễm môi trường biển.",
    "Cấm thực hành đặt loài, tài nguyên biển vào rủi ro tổn hại, khai thác, cạn kiệt thêm.",
    "Đóng góp phát triển công nghệ quản lý chất thải giảm sử dụng nước sạch.",
    "Tổng lượng nước xả theo chất lượng và nơi đến.",
    "Không dùng nhựa dễ phát tán ra biển, thu gom rác bờ biển, truy xuất thủy sản.",
)

_g(
    15,
    "Bảo vệ, phục hồi, thúc đẩy sử dụng bền vững hệ sinh thái trên cạn, quản lý rừng bền vững, chống sa mạc hóa, ngăn chặn, đảo ngược suy thoái đất, ngăn chặn mất đa dạng sinh học.",
    "Đến năm 2020, bảo đảm bảo tồn, phục hồi, sử dụng bền vững hệ sinh thái trên cạn, nước ngọt nội địa và dịch vụ của chúng, đặc biệt rừng, đất ngập nước, núi, vùng khô hạn.",
    "Đến năm 2020, thúc đẩy thực hiện quản lý bền vững mọi loại rừng, chấm dứt phá rừng, phục hồi rừng đã suy thoái, tăng đáng kể trồng rừng, tái trồng rừng toàn cầu.",
    "Đến năm 2030, chống sa mạc hóa, phục hồi đất, đất bị suy thoái, kể cả đất bị ảnh hưởng sa mạc hóa, hạn hán, lũ, nỗ lực đạt thế giới không suy thoái đất.",
    "Đến năm 2030, bảo đảm bảo tồn hệ sinh thái núi, kể cả đa dạng sinh học, để tăng cường khả năng cung cấp lợi ích thiết yếu cho phát triển bền vững.",
    "Hành động khẩn cấp, đáng kể để giảm suy thoái môi trường sống tự nhiên, ngăn chặn mất đa dạng sinh học, đến năm 2020 bảo vệ, ngăn chặn tuyệt chủng các loài bị đe dọa.",
    "Thúc đẩy chia sẻ công bằng, bình đẳng lợi ích từ sử dụng nguồn gen, thúc đẩy tiếp cận phù hợp nguồn gen.",
    "Hành động khẩn cấp chấm dứt săn bắt, buôn bán trái phép loài động thực vật được bảo vệ, giải quyết cả cung và cầu sản phẩm bất hợp pháp.",
    "Đến năm 2020, đưa ra biện pháp ngăn chặn đưa vào, kiểm soát, xóa bỏ các loài ngoại lai xâm hại trên hệ sinh thái đất, nước, kiểm soát hoặc xóa bỏ loài ưu tiên.",
    "Đến năm 2020, lồng ghép giá trị hệ sinh thái, đa dạng sinh học vào quy hoạch quốc gia, địa phương, quy trình phát triển, chiến lược, báo cáo giảm nghèo.",
    "Huy động, tăng đáng kể nguồn lực tài chính từ mọi nguồn để bảo tồn, sử dụng bền vững đa dạng sinh học, hệ sinh thái.",
    "Huy động nguồn lực đáng kể từ mọi nguồn, mọi cấp để tài trợ quản lý rừng bền vững, cung cấp động lực phù hợp cho nước đang phát triển để quản lý rừng bền vững, kể cả bảo tồn, tái trồng rừng.",
    "Tăng hỗ trợ toàn cầu cho nỗ lực chống săn bắt, buôn bán trái phép loài được bảo vệ, kể cả tăng năng lực cộng đồng địa phương theo đuổi cơ hội sinh kế bền vững.",
    "Doanh nghiệp và hệ sinh thái gắn liền. Công ty ảnh hưởng hệ sinh thái vì dựa vào dịch vụ cung cấp như nước ngọt, sợi, lương thực và dịch vụ điều tiết như khí hậu, kiểm soát lũ, lọc nước.",
    "Phá rừng và suy thoái rừng.",
    "Đa dạng di truyền nông trại và vật nuôi thuần hóa.",
    "Phục hồi đất.",
    "Quản lý cảnh quan rừng và thu mua sợi.",
    "Hệ sinh thái núi.",
    "Suy thoái môi trường sống tự nhiên.",
    "Hệ sinh thái trên cạn và nước ngọt nội địa.",
    "Đo lường, quản lý, giảm thiểu tác động lên hệ sinh thái và tài nguyên thiên nhiên.",
    "Mở rộng thực hành tốt về quy hoạch, quản lý sử dụng đất.",
    "Đầu tư hạ tầng tự nhiên như lựa chọn cạnh tranh chi phí so với hạ tầng xám.",
    "Tài trợ phục hồi đất suy thoái cho mục đích sản xuất hoặc bảo tồn.",
    "Mở rộng thị trường sản phẩm rừng có trách nhiệm, hỗ trợ quản lý rừng bền vững.",
    "Không phá rừng, chứng chỉ FSC/PEFC, bảo tồn đa dạng sinh học tại dự án.",
)

_g(
    16,
    "Thúc đẩy xã hội hòa bình, bao trùm vì phát triển bền vững, cung cấp tiếp cận công lý cho tất cả, xây dựng thể chế hiệu quả, chịu trách nhiệm, bao trùm ở mọi cấp.",
    "Giảm đáng kể mọi hình thức bạo lực và tỷ lệ tử vong liên quan ở mọi nơi.",
    "Chấm dứt lạm dụng, bóc lột, buôn bán, mọi hình thức bạo lực, tra tấn đối với trẻ em.",
    "Thúc đẩy nhà nước pháp quyền ở cấp quốc gia, quốc tế, bảo đảm tiếp cận công lý bình đẳng cho tất cả.",
    "Đến năm 2030, giảm đáng kể dòng chảy bất hợp pháp tài chính, vũ khí, tăng cường thu hồi, trả lại tài sản bị đánh cắp, chống mọi hình thức tội phạm có tổ chức.",
    "Giảm đáng kể tham nhũng, hối lộ dưới mọi hình thức.",
    "Phát triển thể chế hiệu quả, chịu trách nhiệm, minh bạch ở mọi cấp.",
    "Bảo đảm ra quyết định đáp ứng, bao trùm, có sự tham gia, đại diện ở mọi cấp.",
    "Mở rộng, tăng cường sự tham gia của các nước đang phát triển vào các thể chế quản trị toàn cầu.",
    "Đến năm 2030, cung cấp danh tính pháp lý cho tất cả, kể cả khai sinh.",
    "Bảo đảm tiếp cận công chúng đối với thông tin, bảo vệ quyền tự do cơ bản, phù hợp pháp luật quốc gia, thỏa thuận quốc tế.",
    "Tăng cường thể chế quốc gia liên quan, kể cả qua hợp tác quốc tế, để xây dựng năng lực ở mọi cấp, đặc biệt nước đang phát triển, nhằm ngăn chặn bạo lực, chống khủng bố, tội phạm.",
    "Thúc đẩy, thực thi luật, chính sách không phân biệt đối xử vì phát triển bền vững.",
    "Doanh nghiệp thịnh vượng trong môi trường hòa bình với thể chế hiệu quả, chi phí vận hành dự đoán được, môi trường làm việc ổn định.",
    "Quản trị hiệu quả, chịu trách nhiệm, minh bạch.",
    "Tuân thủ pháp luật và quy định.",
    "Chống tham nhũng.",
    "Tiếp cận thông tin của công chúng.",
    "Di dời vật lý và kinh tế.",
    "Ra quyết định bao trùm.",
    "Tuân thủ luật, hướng tới chuẩn mực quốc tế; yêu cầu và hỗ trợ đối tác kinh doanh làm tương tự.",
    "Đo lường, báo cáo tiến độ thực hiện, kể cả hoạt động tại khu vực rủi ro cao.",
    "Công ty có tuyên bố công khai sẽ chống tham nhũng dưới mọi hình thức, kể cả hối lộ và tống tiền hay không?",
    "Đạo đức kinh doanh, kênh tố giác, phòng chống rửa tiền, xung đột lợi ích.",
    "Bảo vệ người tố cáo, minh bạch thuế, chống hối lộ trong chuỗi cung ứng.",
    "Quyền con người, an ninh, đối thoại với cộng đồng, khiếu nại, đền bù.",
)

_g(
    17,
    "Tăng cường phương thức thực hiện và làm sống lại đối tác toàn cầu vì phát triển bền vững.",
    "Tăng cường huy động nguồn lực trong nước, kể cả qua hỗ trợ quốc tế cho nước đang phát triển, để cải thiện năng lực thu thuế và nguồn thu khác.",
    "Các nước phát triển thực hiện đầy đủ cam kết hỗ trợ phát triển chính thức, kể cả cam kết 0,7% ODA/GNI cho nước đang phát triển và 0,15–0,20% ODA/GNI cho nước kém phát triển.",
    "Huy động thêm nguồn lực tài chính cho nước đang phát triển từ nhiều nguồn.",
    "Hỗ trợ nước đang phát triển đạt bền vững nợ dài hạn qua chính sách phối hợp nhằm tài trợ, giảm, tái cơ cấu nợ, xử lý nợ bên ngoài của nước nghèo Heavily Indebted Poor Countries.",
    "Áp dụng, thực hiện chế độ thúc đẩy đầu tư cho các nước kém phát triển.",
    "Tăng cường hợp tác Bắc–Nam, Nam–Nam, tam giác khu vực, quốc tế về tiếp cận khoa học, công nghệ, đổi mới, tăng chia sẻ tri thức.",
    "Thúc đẩy phát triển, chuyển giao, phổ biến công nghệ thân thiện môi trường cho nước đang phát triển với điều khoản thuận lợi.",
    "Vận hành đầy đủ ngân hàng công nghệ, cơ chế xây dựng năng lực khoa học, công nghệ, đổi mới cho nước kém phát triển.",
    "Tăng cường hỗ trợ quốc tế cho thực hiện xây dựng năng lực hiệu quả, có mục tiêu ở nước đang phát triển để hỗ trợ kế hoạch quốc gia thực hiện mọi SDG.",
    "Thúc đẩy hệ thống thương mại đa phương phổ quát, dựa luật, mở, không phân biệt, công bằng dưới WTO, kể cả kết thúc vòng đàm phán Doha.",
    "Tăng đáng kể xuất khẩu của nước đang phát triển, nhằm tăng gấp đôi tỷ trọng xuất khẩu toàn cầu của nước kém phát triển đến năm 2020.",
    "Thực hiện kịp thời tiếp cận thị trường không hạn ngạch, không thuế quan trên cơ sở lâu dài cho mọi nước kém phát triển, phù hợp quyết định WTO.",
    "Tăng cường ổn định kinh tế vĩ mô toàn cầu, kể cả qua phối hợp chính sách, nhất quán chính sách.",
    "Tăng cường nhất quán chính sách vì phát triển bền vững.",
    "Tôn trọng không gian chính sách, lãnh đạo của mỗi quốc gia để thiết lập, thực hiện chính sách xóa nghèo, phát triển bền vững.",
    "Tăng cường đối tác toàn cầu vì phát triển bền vững, bổ sung bởi đối tác đa bên huy động, chia sẻ tri thức, chuyên môn, công nghệ, nguồn lực tài chính.",
    "Khuyến khích, thúc đẩy đối tác công, công–tư, xã hội dân sự hiệu quả, xây trên kinh nghiệm, chiến lược nguồn lực của đối tác.",
    "Đến năm 2020, tăng hỗ trợ xây dựng năng lực cho nước đang phát triển nhằm tăng đáng kể sẵn có dữ liệu chất lượng cao, kịp thời, tin cậy, tách theo thu nhập, giới, tuổi, chủng tộc, dân tộc, tình trạng di cư, khuyết tật, vị trí địa lý.",
    "Đến năm 2030, dựa trên sáng kiến hiện có, xây đo lường tiến bộ phát triển bền vững bổ sung GDP, hỗ trợ xây dựng năng lực thống kê ở nước đang phát triển.",
    "Dữ liệu, giám sát và trách nhiệm giải trình.",
    "Hợp tác với nhà cung cấp, khách hàng, cộng đồng, nhà nước, tổ chức quốc tế để thực hiện SDG.",
    "Công bố báo cáo bền vững, đối tác đa bên, chuyển giao công nghệ, chuỗi cung ứng có trách nhiệm.",
    "Tham gia hiệp hội ngành, sáng kiến UN Global Compact, GRI, hỗ trợ nhà cung cấp nhỏ nâng năng lực ESG.",
)


def build_sdg_vi_frame():
    import pandas as pd

    rows = []
    for goalnum, sentence in _ROWS:
        gpnum = GOAL_TO_GP[goalnum]
        rows.append(
            {
                "gpnum": gpnum,
                "gpname": GP_NAME[gpnum],
                "goalnum": goalnum,
                "sentence": sentence,
            }
        )
    return pd.DataFrame(rows)
